name: Run app.js

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run app.js
        run: node app.js
